
title: My Resume
url: 'http://junlulocky.com'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Jadson S Mattos  ## put your name
title: 'DEVELOPER FULL-STACK'  ## your title
location: Brazil


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com/in/jadsonmattos  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url

# collections:
#   - projects

# Update all the sections by editing the files inside _includes folder.
